### ISSUE TITLE
Can't ride

### ISSUE THREAD

**Issue by mmahdi-sz** [TheCymaera/minecraft-spider#12]
hi
i make server with **purpur-1.21.1-2299**
And when I ride, the spider moves, but I sit still
![2024-08-30_14 18 41](https://github.com/user-attachments/assets/61e301f0-6a51-483c-ba1e-74f137ef629a)

video:
https://github.com/user-attachments/assets/dbc2e04b-8d0a-4ef1-a5e9-b3442c93a0c1

note : i have gsit plugin

**Comment by TheCymaera** [comment]
You need to enable command blocks. I used a weird trick for teleportation as Bukkit unmounts entities when they are teleported.

**Comment by mmahdi-sz** [comment]
how can i enable commad block ??
