### ISSUE TITLE
Items not working

### ISSUE THREAD

**Issue by DiscoBohne** [TheCymaera/minecraft-spider#19]
i cant spawn the spider with items. i have done everything said in the description, but the spider wont spawn with the items. the demo command block works. i have turned the gamemode to creative and i have given myself OP, but it still wont spawn.

**Comment by TheCymaera** [comment]
Did you install the beta pre-release? If so, you need to use the `/items` command to get the items instead.

**Comment by DiscoBohne** [comment]
it worked. thanks.
