### ISSUE TITLE
Can't load into minecraft.

### ISSUE THREAD

**Issue by SirBlueAxolotl** [TheCymaera/minecraft-spider#2]
Despite my efforts to load everything correctly, I am encountering an issue where the desired files or components are not being loaded properly. It's unclear why this is happening, and I'm struggling to troubleshoot it. Any insights or suggestions would be greatly appreciated.

**Comment by TheCymaera** [comment]
What errors are you getting in the output? Check that the server version matches the one specified in pom.xml.
