### ISSUE TITLE
How to load

### ISSUE THREAD

**Issue by BluAxoVR** [TheCymaera/minecraft-spider#4]
How do I load this into Minecraft to show my friends?

**Comment by wordandahalf** [comment]
You compile it and copy the built JAR into the plugins folder of your server.

**Comment by BluAxoVR** [comment]
what loader? fabric or forge?

**Comment by BluAxoVR** [comment]
and version

**Comment by wordandahalf** [comment]
It's a Spigot plugin, it's not a mod. 1.20.4.

**Comment by BluAxoVR** [comment]
how do i join the paper server I just made

**Comment by BluAxoVR** [comment]
My problem was I used the 32-bit version of JVM, now I'm using 64-bit and it works.
